import type { Metadata } from "next";
import { Red_Hat_Display } from "next/font/google"; // Import Red_Hat_Display
import "./globals.css";

// Configure Red Hat Display
const redHatDisplay = Red_Hat_Display({
  variable: "--font-red-hat-display", // Define CSS variable
  subsets: ["latin"],
  weight: ["400", "500", "700"], // Specify desired weights
  style: ["normal", "italic"], // Optional: include italic if needed
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${redHatDisplay.variable} antialiased`} // Add redHatDisplay.variable
      >
        {children}
      </body>
    </html>
  );
}
